# https://docs.netlify.com/configure-builds/file-based-configuration/#build-settings
[build]
  base = ""
  publish = "packages/website/build"
  command = "NX_VERBOSE_LOGGING=true yarn patch-package && yarn nx build website"
[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_FLAGS = "--ignore-scripts"

# https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

[[redirects]]
  from = "/docs/*"
  to = "/"

[[redirects]]
  from = "/docs/linting/type-linting"
  to = "/linting/typed-linting"

[[redirects]]
  from = "/docs/linting/monorepo"
  to = "/linting/typed-linting/monorepos"

[[redirects]]
  from = "/docs/linting/tslint"
  to = "/linting/troubleshooting/tslint"
