[build]
  # This is the directory to change to before starting a build.
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  base    = "website/"
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "website/build/"
  # This will be your default build command
  command = "yarn build"
