blank_issues_enabled: false
contact_links:
  - name: FAQ
    about: Please check out our FAQ before filing new issues
    url: https://typescript-eslint.io/docs/linting/troubleshooting
  - name: Getting Started Guide
    about: If you're looking for help setting up check out our getting started guide
    url: https://typescript-eslint.io/docs/
