name: Close issues related to a merged pull request based on v8 branch.

on:
  pull_request:
    types: [closed]
    branches:
      - v8

jobs:
  close_v8_issue_on_pr_merge:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
