name: Update Sponsors Data

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  PRIMARY_NODE_VERSION: 16

jobs:
  build:
    name: Commit if needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Get yarn cache directory path and node version for cache key
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
          echo "::set-output name=node_version::$(node --version)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ steps.yarn-cache-dir-path.outputs.node_version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.yarn-cache-dir-path.outputs.node_version }}-yarn-

      - name: Install dependencies
        run: |
          yarn --ignore-engines --frozen-lockfile --ignore-scripts

      - name: Get typescript-eslint Github app token
        id: get_token
        uses: machine-learning-apps/actions-app-token@2d92b2a2bb7030dca3dd14975ae44799debed2e8
        with:
          APP_PEM: ${{ secrets.GH_APP_PEM }}
          APP_ID: ${{ secrets.GH_APP_ID }}

      - name: Generate sponsors
        run: yarn generate-sponsors

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.get_token.outputs.app_token }}
          commit-message: "chore: update sponsors"
          title: "chore: update sponsors"
          body: "ðŸ’¸"
          branch: auto-update-sponsors
          committer: typescript-eslint[bot] <noreply@github.com>
